spring.application.name=makemytrip
server.port=${PORT:8081}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=makemytrip
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
upload.dir=uploads
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


