spring.application.name=makemytrip
server.port=${PORT:8081}
spring.data.mongodb.uri=mongodb+srv://goyalmahipal089:%40Chitransh123@cluster0.pwc53mu.mongodb.net/makemytrip?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=makemytrip
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
upload.dir=uploads


