spring.application.name=makemytrip
server.port=${PORT:8081}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=makemytrip
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
upload.dir=uploads
cloudinary.cloud-name=hmnxli0o
cloudinary.api-key=887926621269233
cloudinary.api-secret=JfaRMcN28zb59nhJJfbq3Vy4OCc


